version: "3"

services:
  slp:
    image: stardrewer/slp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      - TZ=Asia/Shanghai
    # volumes:
    #   - ./docs:/slp/docs