name: CI
on:
  push:
    branches:
      - master
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: make build
      - name: push
        run: make push
      
